# Generated by Django 3.1.1 on 2024-08-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_add_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_add_stock',
            field=models.BooleanField(default=False),
        ),
    ]
