# Generated by Django 3.1.1 on 2024-08-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpart',
            name='raw_material',
        ),
        migrations.AddField(
            model_name='subpart',
            name='raw_materials',
            field=models.ManyToManyField(through='inventory.SubPartRawMaterial', to='inventory.RawMaterial'),
        ),
    ]
