# Generated by Django 3.1.1 on 2024-10-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpart',
            name='colors',
        ),
    ]
